sonar.projectKey=ProyectoIntegrador3-Galpyra_PI3-Develop
sonar.organization=proyectointegrador3-galpyra
sonar.projectName=PI3-Develop
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/*.pyo,alembic/**
