sonar.projectKey=ProyectoIntegrador3-Galpyra_Pi3-Backend
sonar.organization=proyectointegrador3-galpyra

sonar.sources=app
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
