# Identificación del proyecto en SonarCloud
sonar.projectKey=ProyectoIntegrador3-Galpyra_PI3-Develop
sonar.organization=proyectointegrador3-galpyra

# Nombre que aparecerá en SonarCloud
sonar.projectName=PI3-Develop
sonar.projectVersion=1.0

# Carpeta donde está el código backend
sonar.sources=app

# Carpeta de pruebas
sonar.tests=tests

# Reporte de cobertura generado por pytest
sonar.python.coverage.reportPaths=coverage.xml

# Encoding
sonar.sourceEncoding=UTF-8

# Archivos que Sonar debe ignorar
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/*.pyo,alembic/**
