name: Test Backend Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Workflow detectado correctamente"
